# Day 13

# Slicing of NumPy Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [3]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


# Slicing in 2D Array

In [6]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,1:4])

[70 80 90]


In [8]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[1,0:3])

[60 70 80]


In [11]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a[0,0:3])

[10 20 30]


# Checking the Data Type of an Array

In [12]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [13]:
arr = np.array(['animals','bat','cat'])
print(arr.dtype)

<U7


# Creating Arrays with the define data type

In [14]:
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Create an Array with datatypes 4 bytes integer

In [17]:
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# Numpy Array Shape

#### The shape of an array is the number of elements in each dimension

# Print the shape of a 2D Array

In [18]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


# Print the Shape of a 3D Array

In [21]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
print(arr.shape)

(1, 3, 4)


# Joining Numpy Arrays

In [24]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [27]:
arr3 = np.array([2,3,4,5])
arr4 = np.array([6,7,8,9])
arr = np.concatenate((arr3, arr4))
print(arr)

[2 3 4 5 6 7 8 9]


# Join 2D Arrays

In [28]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2),axis =1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [29]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1, arr2),axis =0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting Numpy Arrays

# Spliting the array in 3 parts

In [30]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [31]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


# Spliting the array in 4 parts

In [32]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Ravel & Flatten

### Converts multidimensional array into 1D array

In [38]:
m = np.array([[[1,2,3],[4,5,6,],[7,8,9]]])
print(m)
print("dimension is ", m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is ", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
now the new dimension is  1


In [39]:
m = np.array([[[1,2,3],[4,5,6,],[7,8,9]]])
print(m)
print("dimension is ", m.ndim)
n = m.flatten()
print(n)
print("now the new dimension is ", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is  3
[1 2 3 4 5 6 7 8 9]
now the new dimension is  1


In [43]:
c = np.array([[[[1,2,3],[78,89,25],[45,26,84]]]])
print(c)
print("the dimension is", c.ndim)
d = c.ravel()
print(d)
print("now the new dimension is", d.ndim)

[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]
the dimension is 4
[ 1  2  3 78 89 25 45 26 84]
now the new dimension is 1


In [44]:
c = np.array([[[[1,2,3],[78,89,25],[45,26,84]]]])
print(c)
print("the dimension is", c.ndim)
d = c.flatten()
print(d)
print("now the new dimension is", d.ndim)

[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]
the dimension is 4
[ 1  2  3 78 89 25 45 26 84]
now the new dimension is 1


# Unique Function

In [45]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
[ 1  2  3  4  5  6  7  9 12 22 33]


In [46]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64))


In [47]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True, return_counts = True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64), array([2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1], dtype=int64))


In [48]:
a = np.array([12,13,14,15])
d = np.delete(a, [1])
print(d)

[12 14 15]


In [53]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
print(x)
m = np.delete(x, 1, axis = 0)
print()
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 2  7  9  6  8]
 [50  0 65  6  7]]
